services:
  webapp:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: ${DOCKER_IMAGE_NAME_WEBAPP}:${DOCKER_IMAGE_TAG_WEBAPP}
    container_name: ${DOCKER_CONTAINER_BASENAME_APP}-webapp
    ports:
      - ${DOCKER_WEBAPP_PORT}:8080
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
